### ISSUE TITLE
U of Wyoming sounding data

### ISSUE THREAD

**Issue by winash12** [SciTools/tephi#12]
I have data from U of Wyoming soundings - http://weather.uwyo.edu/upperair/sounding.html. As an example here we go - http://weather.uwyo.edu/cgi-bin/sounding?region=seasia&TYPE=TEXT%3ARAW&YEAR=2019&MONTH=03&FROM=2000&TO=2000&STNM=43279. Can your software read that format and plot it ?

**Comment by bjlittle** [comment]
@winash12 Apologies for the tardy response, I'm sure that you've forgotten about this issue or it's now no longer relevant.

The `tephi` package expects data to be provided to it as `(pressure, temperature)` pairs, see the [documentation](https://tephi.readthedocs.io/en/latest/plotting.html#tephigram-data) for further details. So in this case, you'd need to do a little bit of pre-processing to massage your data into this format.

I'm going to close this issue, as I'm sure it has gone stale. If you require further support, then please do just open another issue.
