### ISSUE TITLE
No module named isopleths

### ISSUE THREAD

**Issue by ApexPlus-Tech** [SciTools/tephi#13]
Installing tephi is successful . However, when I use it in a module it gives me an error . No module named isopleths . When I try to install isopleths using pip it gives me an error "No matching distribution found for isopleths".

**Comment by pelson** [comment]
I'm not sure you've installed it correctly, isopleths is a submodule within this package. Can you provide the steps you took to install tephi, your full environment information (incl how you installed python and which platform you are on) and the traceback please?

Thanks!

**Comment by bjlittle** [comment]
@ApexPlus-Tech Apologies for the super tardy response.

The `tephi` package infrastructure has recently been updated and the latest version is available on [PyPI](https://pypi.org/project/tephi/), please give that a try.

I'm going to close this issue, but if this is still a problem for you then please re-open this issue and we'll investigate further. Thanks.
