### ISSUE TITLE
module 'tephi' has no attribute 'Tephigram'`

### ISSUE THREAD

**Issue by winash12** [SciTools/tephi#56]
With this line of code I get 

`tpg = tephi.Tephigram()`

`Traceback (most recent call last):
  File "tephi.py", line 9, in <module>
    import tephi
  File "/home/winash12/soundings/tephi.py", line 28, in <module>
    tpg = tephi.Tephigram()
AttributeError: module 'tephi' has no attribute 'Tephigram'`

**Comment by winash12** [comment]
Here is the odd part - 

if I run this as root i.e. python 3.6 

`from tephi import Tephigram`

no problems. But when I run this as myself

I get 

`Traceback (most recent call last):
  File "tephi.py", line 9, in <module>
    from tephi import Tephigram
  File "/home/winash12/soundings/tephi.py", line 9, in <module>
    from tephi import Tephigram
ImportError: cannot import name 'Tephigram'`

**Comment by bjlittle** [comment]
Hi @winash12, good to hear from you.

What version of `tephi` are you using?

**Comment by bjlittle** [comment]
The latest version of `tephi` available on PyPI is `0.2.4`. The `tephi` package will also be available on `conda-forge` soon.

**Comment by winash12** [comment]
The version of Python is 0.2.4.  The version of Python is 3.6. Platform is Ubuntu 18.04 LTS.

**Comment by bjlittle** [comment]
@winash12 Are you using `pip` to install `tephi` or just downloading the source and running that?

**Comment by winash12** [comment]
@bjlittle python3.6 setup.py install

**Comment by bjlittle** [comment]
@winash12 So just to confirm, you're downloading the source then installing via `setuptools` using `setup.py`, right?

**Comment by winash12** [comment]
> @winash12 So just to confirm, you're downloading the source then installing via `setuptools` using `setup.py`, right?

Yes. Using that command . I do not know if  `setuptools` is being used in the background. No conda or virtualenv.

**Comment by bjlittle** [comment]
@bjlittle Cool, thanks. I'll investigate this side to see if I can recreate your issue and get back to you asap.

**Comment by winash12** [comment]
`Traceback (most recent call last):
  File "tephi.py", line 9, in <module>
    from tephi import Tephigram
  File "/home/winash12/soundings/tephi.py", line 9, in <module>
    from tephi import Tephigram
ImportError: cannot import name 'Tephigram'
`
This is the error I get now.

**Comment by bjlittle** [comment]
@winash12 Sadly, I can't recreate your issue...

I'm assuming that when you performed the `python setup.py install` that command ran successfully with no traceback, right?

If so, you should be able to perform the following command from the terminal `python -c "import tephi; print(tephi)"` successfully.

However, can I just check... is the script that you are calling to do your tephigram plotting called `tephi.py` by any chance? I'm just wondering whether this is the issue.

To confirm this, you should be able to do the following:
```bash
> mkdir delme
> cd delme
> python -c "import tephi; from tephi import Tephigram; print(Tephigram)"
<class 'tephi.Tephigram'>
```
If this works then it may be that you require to rename your `/home/winash12/soundings/tephi.py` script to be something else e.g., `main.py` or `plot.py`

**Comment by winash12** [comment]
@bjlittle Bingo ! That was the problem. It  cannot be named tephi.py. It has to be named something else.

**Comment by bjlittle** [comment]
Yup, I've fallen foul of this before. It can be REALLY confusing.

Your `tephi` is being used before `scitools/tephi` and of course hence the problem.

Glad to hear that it worked for you :smile:

**Comment by winash12** [comment]
https://imgur.com/a/bWyesYX For closure.

**Comment by bjlittle** [comment]
@winash12 I'm interested in your use case of `tephi`... I'm always looking to improve and extend the functionality. So if you have any suggestions I'd love to hear them.

Sadly I've not really had time to show much love to `tephi` in a long while, but I'm keen to invest more development time in it - so if you have any feature requests, issues or niggles... I'd love to hear from you. Thanks!

**Comment by winash12** [comment]
@bjlittle So my country's meteorological department uses this - https://i.stack.imgur.com/v4Iif.gif format for displaying tephigrams. I am trying to reproduce the same in a more consistent international format. So yea I will keep you posted.

**Comment by bjlittle** [comment]
Awesome.

I'll be looking to add CAPE and CIN calculations into `tephi`, so you may benefit from that.

Also note that I've added `binder` to the repo, so you can play with `tephi` in a Jupyter notebook in the cloud and it will install all the associated dependencies in the environment.

Click the `launch binder` badge (penultimate badge) in the repo [README.md](https://github.com/SciTools/tephi/blob/master/README.md).

HTH

**Comment by winash12** [comment]
@bjlittle Is it possible to orient the isobars in the same way as my country's meteorological department is doing?

**Comment by bjlittle** [comment]
@winash12 Hmmm yes, it would be possible, but then again it wouldn't really be a tephigram, to be honest.

I guess you'd want to be able to control the units of the potential temperature to be Kelvin instead of Celsius too.

Leave it with me. I may be able to make this customisable for you.

Are you working to a deadline? I'm only asking as I have limited resources to spend on tephi development.

**Comment by winash12** [comment]
@bjlittle Not at all. No deadline whatsoever. Whenever you feel like you got an update for me  I will  be willing to try what you got. Thanks.

**Comment by bjlittle** [comment]
@winash12 This seems kinds close to what you want...
![image](https://user-images.githubusercontent.com/2051656/83233441-9a061180-a186-11ea-9188-067aaa26d33f.png)

**Comment by bjlittle** [comment]
BTW what meteorological organisation do you work for? Don't feel you have to answer this, I'm just curious :smile:

**Comment by winash12** [comment]
> @winash12 This seems kinds close to what you want...
> ![image](https://user-images.githubusercontent.com/2051656/83233441-9a061180-a186-11ea-9188-067aaa26d33f.png)
> Note that, I've hacked `tephi` to make this kind of plot... so ultimately to make it useful to you, I'd have to make it customisable from the API level... which seems possible, but will require a bit of thought and effort to make it slick from the user experience perspective.

@bjlittle Outstanding !  Sample code for generating this ? I work for a commercial establishment not an org.

**Comment by winash12** [comment]
The isobars seem missing in this or am I missing something ?

**Comment by winash12** [comment]
The black line in the middle - what is that ?

**Comment by bjlittle** [comment]
> The black line in the middle - what is that ?

It's the 0 oC isotherm, which can be turned off easily

**Comment by bjlittle** [comment]
> The isobars seem missing in this or am I missing something ?

The isobars are there, as per your example. They are the light blue, dashed lines, cutting across the plot from bottom-left to top-right, and are labelled.

**Comment by bjlittle** [comment]
> Outstanding ! Sample code for generating this ?

I've pushed the changes that generated this plot into the feature branch https://github.com/bjlittle/tephi/tree/winash12

The script that generated the plot is https://github.com/bjlittle/tephi/blob/winash12/runme.py

I guess you can checkout that branch and play / install from source, if that helps.
